name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
#          - '5.24'
#          - '5.26'
#          - '5.28'
#          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: install minimal dependencies
        run: cpanm -n --no-interactive --installdeps --skip-satisfied .
      - name: run minimal tests
        env:
          SPREADSHEET_COMPARE_DEBUG: INFO
        run: prove -Ilib -m -v --jobs 4
      - name: install all dependencies
        env:
          SPREADSHEET_COMPARE_TEST_ALL: 1
        run: cpanm -n --no-interactive --installdeps --skip-satisfied .
      - name: run all tests
        env:
          SPREADSHEET_COMPARE_DEBUG: INFO
          SPREADSHEET_COMPARE_TEST_ALL: 1
        run: prove -Ilib -m -v --jobs 4
