name: windows
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run:  |
              git config --global core.autocrlf false
              git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: perl -V
        run:  perl -V
      - name:  set path
        shell: bash
        run:   echo 'C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin' >> $GITHUB_PATH
      - name: install minimal dependencies
        run:  cpanm -f -n --no-interactive --installdeps --skip-satisfied .
      - name: run minimal tests
        env:
          SPREADSHEET_COMPARE_DEBUG: INFO
        run:  prove -Ilib -m -v --jobs 4
      - name: install Mojo::IOLoop::Thread
        run:  cpanm -f -n --no-interactive Mojo::IOLoop::Thread
      - name: run multithreaded test
        env:
          SPREADSHEET_COMPARE_DEBUG: INFO
        run:  prove -Ilib -m -v
      - name: install all dependencies
        env:
          SPREADSHEET_COMPARE_TEST_ALL: 1
        run:  cpanm -f -n --no-interactive Mojo::IOLoop::Thread
      - name: run all tests
        env:
          SPREADSHEET_COMPARE_TEST_ALL: 1
          SPREADSHEET_COMPARE_DEBUG: INFO
        run:  prove -Ilib -m -v
